CREATE TABLE cd_conta_contabil (
    DATA DATE NOT NULL,
    REG_ANS INT,
    CD_CONTA_CONTABIL VARCHAR(50),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2),
    FOREIGN KEY (REG_ANS) REFERENCES operadoras_ativas(REG_ANS)
);
